config/routes.rb
Rails.application.routes.draw do
  

  get 'dashboards/index'
  devise_for :users
  devise_scope :user do
  root to: "devise/sessions#new"
  end

  resources :products do
	  collection do
	  	get 'trash' => "products#trash", :as => :trash
	  	get 'product_trash' => "products#product_trash", :as => :products_trash
	  	get 'restore' => "products#restore", :as => :restore
	  end
	end

	resources :companies do
	  collection do
	  	get 'trash' => "companies#trash", :as => :trash
	  	get 'company_trash' => "companies#company_trash", :as => :companies_trash
	  	get 'restore' => "companies#restore", :as => :restore
	  end
	end

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :products, :dependent => :delete_all
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :Company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :gender, presence: true
  # validates :phone, presence: true      
  # validates :email,presence: true
  # validates :password,presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_sign_up_params, :configure_account_update_params, :configure_permitted_parameters, if: :devise_controller?


  	def configure_sign_up_params
		 devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :password, :first_name, :last_name, :gender, :phone, :password_confirmation])
	end

	def configure_account_update_params
	     devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :first_name, :last_name, :gender, :phone])
	end

    def configure_permitted_parameters
	    update_attrs = [:password, :password_confirmation, :current_password]
	    devise_parameter_sanitizer.permit :account_update, keys: update_attrs
	end 

	def after_sign_in_path_for(resource_or_scope)
		 companies_path
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
layout 'admin'
 
    def create
      abort params.inspect
      @admin_company = Company.new(create_patams)
       if @admin_company.save 
           redirect_to :action => 'show', :id => @admin_company.id, :notice => "company successFully added"
       else
           render :action => 'new', :alert => "Something Went Wrong"
        end
    end
 
    def index
        @admin_companies = Company.where(c_deleted_at: [nil, ""])
    end

    def new
      @admin_company = Company.new
    end

    def edit
      @admin_company = Company.find(params[:id])
    end
 
    def show
      @admin_company = Company.find(params[:id])
    end
 
    def update
       @admin_company = Company.find(params[:id])
       if @admin_company.update_attributes(create_patams)
          redirect_to :action => 'show', :id => @admin_company.id
       end 
    end
 

    def trash
    trash = Company.find(params[:id])
    trash.update_attributes(c_deleted_at: DateTime.now.to_date)
    redirect_to companies_trash_companies_path

    end

    def company_trash
      @c_trash = Company.where.not(c_deleted_at: [nil, ""])
    end
      
    def restore
      restore = Company.find(params[:id])
      restore.update_attributes(c_deleted_at: nil)
      redirect_to companies_trash_companies_path
    end  

    def destroy
      @admin_company = Company.find(params[:id])
      @admin_product = Product.where(company_id: params[:id])

      @admin_product.each do |ap|
          ap.destroy
      end  
      @admin_company.destroy
      redirect_to :action => 'index'
    end
        
    private
        def create_patams
            params.require(:company).permit(:name, :address, :phone, :email, :data, :image)
        end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
layout 'admin'
  def index
  	@companies = Company.all.count
  	@products = Product.all.count
  	@users = User.all.count
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
layout 'admin'
    def create
      @company = Company.all
      @admin_product = Product.new(create_patams)
       @id = Product.where(id: [@cid])
       if @admin_product.save
           redirect_to :action => 'show', :id => @admin_product.id, :notice => "Product successFully added"
       else
			     render :action => 'new', :alert => "Something Went Wrong"
       end
    end

 
    def index
        @admin_products = Product.where(p_deleted_at: [nil, ""])
    end

    def new
    	@admin_product = Product.new
    	@company = Company.all
    end
 
    def edit
     	@company = Company.all
      @admin_product = Product.find(params[:id])
    end

    def trash
      trash = Product.find(params[:id])
      trash.update_attributes(p_deleted_at: DateTime.now.to_date)
      redirect_to products_trash_products_path
    end

    def product_trash
      @c_trash = Product.where.not(p_deleted_at: [nil, ""])
    end
      
    def restore
      restore = Product.find(params[:id])
      restore.update_attributes(p_deleted_at: nil)
      redirect_to products_trash_products_path
    end 

    def show
        @admin_product = Product.find(params[:id])
    end
 
    def update
       @admin_product = Product.find(params[:id])
       if @admin_product.update_attributes(create_patams)
		    	redirect_to :action => 'show', :id => @admin_product.id
       end 
    end

  def destroy
    @admin_product = Product.find(params[:id])
    @admin_product.destroy
    redirect_to :action => 'index'
  end

    private
        def create_patams
            params.require(:product).permit(:code,:name,:price,:description,:company_id,:image)
             
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/companies/company_trash.html.erb
<% @title = "Companies Trash" %>
<% @titleheader = "Company Trash" %>
<div class="panel panel-flat">
   <div class="panel-heading">
      <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
   </div>
   <table class="table" id="myTable">
      <thead>
         <tr>
            <th>No</th>
            <th>Image</th>
            <th>Company Name</th>
            <th>address</th>
            <th>phone</th>
            <th>email</th>
            <th class="text-center">Actions</th>
         </tr>
      </thead>
      <tbody> <% @no = 1 %>
         <% @c_trash.each do |p| %>
         <tr>
            <td><%= @no %></td>
              <td><%= image_tag("missing.png", :alt => "") %>
              </td>
            <td><a href="<%=company_path(:id=>p.id)%>"><%= p.name %></td>
            <td><%= p.address %></td>
            <td><%= p.phone%></td>
            <td><%= p.email%></td>
            <td class="text-center">
               <ul class="icons-list">
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     <i class="icon-menu9"></i>
                     </a>
                      <ul class="dropdown-menu dropdown-menu-right">
                          <li><a href="<%= company_path(:id=>p.id)%>" data-method="delete" data-confirm="Are you sure?"><i class="icon-bin2"></i>Hard-Delete</a>
                          </li>   
                          <li><a href="<%= restore_companies_path(:id=>p.id)%>"><i class="icon-git-compare"></i>Restore Company</a>
                          </li>                                               
                       </ul>
                  </li>
               </ul>
            </td>
         </tr>
         <% @no = @no + 1 %>
         <%end%>                   
      </tbody>
   </table>

</div>
</div>

</form>
<script type="text/javascript">
   $(document).ready(function(){
     $('#myTable').DataTable({
      autoWidth: false,
        // columnDefs: [{ 
        //     orderable: false,
        //     width: '100px',
        //     targets: [ 5 ]
        // }],
        dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
        language: {
            search: '<span>Filter:</span> _INPUT_',
            lengthMenu: '<span>Show:</span> _MENU_',
            paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
        drawCallback: function () {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
        },
        preDrawCallback: function() {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
        }
     });
     // Alternative pagination
    $('.datatable-pagination').DataTable({
        pagingType: "simple",
        language: {
            paginate: {'next': 'Next &rarr;', 'previous': '&larr; Prev'}
        }
    });


    // Add placeholder to the datatable filter option
    $('.dataTables_filter input[type=search]').attr('placeholder','Type to filter...');


    // Enable Select2 select for the length option
    $('.dataTables_length select').select2({
        minimumResultsForSearch: Infinity,
        width: 'auto'
    });

   });
</script>

app/views/companies/edit.html.erb
  `<% @titleheader = "Company" %>
<div class="panel panel-flat">
  <div class="panel-heading">
     <h5 class="panel-title">Edit Company</h5>
<!--      <div class="heading-elements">
        <ul class="icons-list">
           <li><a data-action="collapse"></a></li>
           <li><a data-action="reload"></a></li>
           <li><a data-action="close"></a></li>
        </ul>
     </div> -->
     <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
  </div>
  <div class="panel-body">
 <% @title = "Company  /  edit" %>
<%= form_for([@admin_company],:html => {:id=>"validate-form"}) do |f| %>
        <fieldset class="content-group">
           <!-- <legend class="text-bold">New</legend> -->
<fieldset class="content-group">
           <div class="form-group">
              <label class="control-label col-lg-2">Company Name</label>
              <div class="col-lg-10">
				  <%= f.text_field :name, :class => "form-control"  %>
              </div>
           </div>
       </fieldset>
<fieldset class="content-group">
            <div class="form-group">
              <label class="control-label col-lg-2">Company Address</label>
              <div class="col-lg-10">
	              <%= f.text_area :address, :class => "form-control"  %> 
              </div>
           </div>
       </fieldset>
           <fieldset class="content-group">
           <div class="form-group">
              <label class="control-label col-lg-2">Company Phone</label>
              <div class="col-lg-10">
				 <%= f.text_field :phone, :class => "form-control"  %>
              </div>
           </div>
       </fieldset>
           <fieldset class="content-group">
            <div class="form-group">
              <label class="control-label col-lg-2">Company email</label>
              <div class="col-lg-10">
	              <%= f.email_field :email, :class => "form-control" %> 
              </div>
           </div>
       </fieldset>


                <div class="col-lg-10">
        </fieldset>

        <div class="text-right">
	<%= f.submit :submit, :class => "btn btn-primary" %>
	<%#= link_to 'Show', admin_companies_path, :class => "btn btn-primary" %>
        </div>
     </form>
  </div>
</div>
<%end%>

app/views/companies/index.html.erb
<% @title = "Companies" %>
<% @titleheader = "Company" %>
<div class="panel panel-flat">
   <div class="panel-heading">
      <h5 class="panel-title">Company</h5>
      <div class="heading-elements">
         <ul class="icons-list inline-flex">
            <a href="<%=new_company_path%>"><button type="button" class="btn btn-primary">Add Company</button> 
            </a>
         </ul>  
      </div>

      <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
   </div>
   <table class="table" id="myTable">
      <thead>
         <tr>
            <th>No</th>
            <th>Image</th>
            <th>Company Name</th>
            <th>address</th>
            <th>phone</th>
            <th>email</th>
            <th class="text-center">Actions</th>
         </tr>
      </thead>
      <tbody> <% @no = 1 %>
         <% @admin_companies.each do |p| %>
         <tr>
            <td><%= @no %></td>
              <td><%= image_tag("missing.png", :alt => "") %>
              </td>
            <td><a href="<%=company_path(:id=>p.id)%>"><%= p.name %></td>
            <td><%= p.address %></td>
            <td><%= p.phone%></td>
            <td><%= p.email%></td>
            <td class="text-center">
               <ul class="icons-list">
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     <i class="icon-menu9"></i>
                     </a>
                      <ul class="dropdown-menu dropdown-menu-right">
                          <li><a href="<%= edit_company_path(:id=>p.id)%>"><i class="icon-database-edit2"></i> Edit</a></li>
                          <li><a href="<%= company_path(:id=>p.id)%>" data-method="delete" data-confirm="Are you sure?"><i class="icon-bin2"></i>Hard-Delete</a>
                          </li>
                          <li><a href="<%= trash_companies_path(:id=>p.id) %>"><i class="icon-bin2"></i>Soft-Delete</a>
                          </li>                          
                          <li><a href="<%= company_path(:id=>p.id)%>"><i class="icon-eye"></i> Show</a></li>
                       </ul>
                  </li>
               </ul>
            </td>
         </tr>
         <% @no = @no + 1 %>
         <%end%>                   
      </tbody>
   </table>

</div>
</div>

</form>
<script type="text/javascript">
   $(document).ready(function(){
     $('#myTable').DataTable({
      autoWidth: false,
        // columnDefs: [{ 
        //     orderable: false,
        //     width: '100px',
        //     targets: [ 5 ]
        // }],
        dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
        language: {
            search: '<span>Filter:</span> _INPUT_',
            lengthMenu: '<span>Show:</span> _MENU_',
            paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
        drawCallback: function () {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
        },
        preDrawCallback: function() {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
        }
     });
     // Alternative pagination
    $('.datatable-pagination').DataTable({
        pagingType: "simple",
        language: {
            paginate: {'next': 'Next &rarr;', 'previous': '&larr; Prev'}
        }
    });


    // Add placeholder to the datatable filter option
    $('.dataTables_filter input[type=search]').attr('placeholder','Type to filter...');


    // Enable Select2 select for the length option
    $('.dataTables_length select').select2({
        minimumResultsForSearch: Infinity,
        width: 'auto'
    });

   });
</script>

app/views/dashboards/index.html.erb
<div class="row">
		<div class="col-lg-4">

			<!-- Members online -->
			<div class="panel bg-teal-400">
				<div class="panel-body">
					<h3 class="no-margin"><%= @users %></h3>
					Total Users
				</div>

				<div class="container-fluid">
					<div id="members-online"></div>
				</div>
			</div>
			<!-- /members online -->

		</div>

		<div class="col-lg-4">

			<!-- Current server load -->
			<div class="panel bg-pink-400">
				<div class="panel-body">

					<h3 class="no-margin"><%= @products %></h3>
					Total Products
				</div>

				
			</div>
			<!-- /current server load -->

		</div>

		<div class="col-lg-4">

			<!-- Today's revenue -->
			<div class="panel bg-blue-400">
				<div class="panel-body">

					<h3 class="no-margin"><%= @companies %></h3>
					Total Companies
				</div>

				
			</div>
			<!-- /today's revenue -->

		</div>
</div>

app/views/layouts/admin/_footer.html.erb
<div class="footer text-muted">
						© 2017. <a href="#">Business Api webkit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Ronak</a>
					</div>

app/views/layouts/admin/_side_bar.html.erb
			<!-- Main sidebar -->
			<div class="sidebar sidebar-main">
				<div class="sidebar-content">

					<!-- User menu -->
					<div class="sidebar-user">
						<div class="category-content">
							<div class="media">
								<a href="#" class="media-left">
						              	<td><%= image_tag("missing.png", :alt => "") %></td>
								</a>
								<div class="media-body">
									<span class="media-heading text-semibold"><%= current_user.first_name %>  <%= current_user.last_name %></</span>
									<div class="text-size-mini text-muted">
										<i class="icon-pin text-size-small"></i> &nbsp;Gujarat, Ahmedabad
									</div>
								</div>

								<div class="media-right media-middle">
<!-- 									<ul class="icons-list">
										<li>
											<a href="#"><i class="icon-cog3"></i></a>
										</li>
									</ul> -->
								</div>
							</div>
						</div>
					</div>
					<!-- /user menu -->


					<!-- Main navigation -->
					<div class="sidebar-category sidebar-category-visible">
						<div class="category-content no-padding">
							<ul class="navigation navigation-main navigation-accordion">

								<!-- Main -->
								<li class="navigation-header"><span>Main</span> <i class="icon-menu" title="" data-original-title="Main pages"></i></li>
								<li>
									<a href="<%= dashboards_index_path %>" class="has-ul"><i class="icon-lifebuoy"></i> <span>Dashboard</span></a>
								</li>
								<li>
									<a href="<%= products_path %>" class="has-ul"><i class="icon-cart"></i> <span>Product</span></a>
								</li>
								<li>
									<a href="<%= products_trash_products_path %>" class="has-ul"><i class="icon-cart"></i> <span>Products Trash</span></a> 

								</li>								

								<li>
									<a href="<%= companies_path %>" class="has-ul"><i class="icon-archive"></i> <span>Company</span></a> 

								</li>
								<li>
									<a href="<%= companies_trash_companies_path %>" class="has-ul"><i class="icon-archive"></i> <span>Companis Trash</span></a> 

								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>

app/views/layouts/login/_footer.html.erb
<div class="footer text-white">
						© 2017. Business Api webkit  by  Ronak
					</div>

app/views/products/index.html.erb
<%#= form_tag import_csv_admin_companies_path, multipart: true do %>
<% @titleheader = "Product" %>
<% @title = "Products" %>
<div class="panel panel-flat">
   <div class="panel-heading">
      <h5 class="panel-title">Products</h5>
      <div class="heading-elements">
         <ul class="icons-list inline-flex">
            <a href="<%=new_product_path%>"><button type="button" class="btn btn-primary">Add Product</button> 
            </a>  
      </div>
      <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
   </div>
     <table class="table" id="myTable">
        <thead>
           <tr>
              <th>Code</th>
              <th>Name</th>
              <th>Price</th>
              <th>Description</th>
              <th>Company Name</th>
              <th class="text-center">Actions</th>
           </tr>
        </thead>
        <tbody>
           <% @admin_products.each do |p| %>
           <tr>
              <td><%= p.code %></td>
              <td><%= p.name %></td>
              <td><%= p.price %></td>
              <td><%= p.description%></td>
              <% if p.Company_id.inspect %>
              <% a = p.Company_id
                 @cmp = Company.find_by_id(a)
              %>
                <td><a href="<%= company_path(:id => @cmp.id)%>"><%= @cmp.name %></a></td>
              <% end %>
              <td class="text-center">
                 <ul class="icons-list">
                    <li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       <i class="icon-menu9"></i>
                       </a>
                       <ul class="dropdown-menu dropdown-menu-right">
                          <li><a href="<%=edit_product_path(:id=>p.id)%>"><i class="icon-database-edit2"></i> Edit</a></li>
                          <li><a href="<%=product_path(:id=>p.id)%>"><i class="icon-eye"></i> Show</a></li>
                          <li><a href="<%= product_path(:id=>p.id)%>" data-method="delete" data-confirm="Are you sure?" id="sweet_combine"><i class="icon-bin2">
                             </i>
                             Hard-Delete</a>
                          </li>
                          <li><a href="<%= trash_products_path(:id=>p.id) %>"><i class="icon-bin2"></i>Soft-Delete</a>
                          </li>                           
                       </ul>
                    </li>
                 </ul>
              </td>
           </tr>
           <%end%>                   
        </tbody>
     </table>
     <tr>
</div>
<script type="text/javascript">
   $(document).ready(function(){
     $('#myTable').DataTable({
      autoWidth: false,
        // columnDefs: [{ 
        //     orderable: false,
        //     width: '100px',
        //     targets: [ 5 ]
        // }],
        dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
        language: {
            search: '<span>Filter:</span> _INPUT_',
            lengthMenu: '<span>Show:</span> _MENU_',
            paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
        drawCallback: function () {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
        },
        preDrawCallback: function() {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
        }
     });
     // Alternative pagination
    $('.datatable-pagination').DataTable({
        pagingType: "simple",
        language: {
            paginate: {'next': 'Next &rarr;', 'previous': '&larr; Prev'}
        }
    });


    // Add placeholder to the datatable filter option
    $('.dataTables_filter input[type=search]').attr('placeholder','Type to filter...');


    // Enable Select2 select for the length option
    $('.dataTables_length select').select2({
        minimumResultsForSearch: Infinity,
        width: 'auto'
    });

   });
</script>

app/views/products/new.html.erb
<% @titleheader = "Product" %>
<div class="panel panel-flat">
   <div class="panel-heading">
      <h5 class="panel-title">New Product</h5>
      <!--      <div class="heading-elements">
         <ul class="icons-list">
            <li><a data-action="collapse"></a></li>
            <li><a data-action="reload"></a></li>
            <li><a data-action="close"></a></li>
         </ul>
         </div> -->
      <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
   </div>
   <div class="panel-body">
      <% @title = "Product  /  New" %>
      <%= form_for @admin_product, url: products_path(@admin_product) do |f| %>   
        <%#= render "error_messages", :target => @admin_product %>


      <fieldset class="content-group">
         <!-- <legend class="text-bold">New</legend> -->
         <fieldset class="content-group">
            <div class="form-group">
               <label class="control-label col-lg-2">Product Code</label>
               <div class="col-lg-6">
                  <%= f.text_field :code, :class => "form-control", :id => "name"  %>
               </div>    
            </div>
         </fieldset>
         <fieldset class="content-group">
            <div class="form-group">
               <label class="control-label col-lg-2">Product Name</label>
               <div class="col-lg-6">
                  <%= f.text_field :name, :class => "form-control"  %> 
               </div>
            </div>
         </fieldset>
         <fieldset class="content-group">
            <div class="form-group">
               <label class="control-label col-lg-2">Description</label>
               <div class="col-lg-6">
                  <%= f.text_area :description, :class => "form-control"  %>
               </div>
            </div>
         </fieldset>
         <fieldset class="content-group">
            <div class="form-group">
               <label class="control-label col-lg-2">Product Price</label>
               <div class="col-lg-6">
                  <%= f.text_field :price, :class => "form-control" %> 
               </div>
            </div>
         </fieldset>
      </fieldset>
      <fieldset class="content-group">
         <div class="form-group">
            <label class="control-label col-lg-2">Company Name</label>
            <div class="col-lg-6">
               <%#= f.select :company_id, options_for_select(@company.collect { |p| [p.name, p.id] }), class: "form-control" %>
               <%= f.select :Company_id, options_for_select(@company.collect { |p| [p.name, p.id] }), {prompt: "Select company"}, class: "form-control" %>
            </div>
         </div>
      </fieldset>
  

      <div class="text-right" data-toggle="modal" data-target="#myModal">
         <%= f.submit :submit, :class => "btn btn-primary" %>
         <%#= link_to 'Show', admin_products_path, :class => "btn btn-primary" %>
      </div>
      </form>
   </div>
</div>
<div id="myModal" class="modal" role="dialog">
   <div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(100%, 0px, 0px);">
  <div class="pace-progress-inner"></div>
</div>
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-content">
        <div class="modal-body">
          <!-- <img src="https://img0bm.b8cdn.com/images/icons/grayLoader.gif"> -->
          <img src="http://price.choicequoter.com/assets/ajax-loader-a83a7b890c6aafe0afeac3afa9fa184cfe99f5dbf01bcbc2d8eee74b464ba993.gif">
          <p>inserting data</p>

         </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>



<script type="text/javascript">

   $(document).ready(function() {
      $("#new_product").submit(function(){
         $('.modal').css('display', 'block');
      });
   });
</script>

app/views/products/product_trash.html.erb
<% @titleheader = "Products Trash" %>
<% @title = "Products Trash" %>
<div class="panel panel-flat">
   <div class="panel-heading">
      <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
   </div>
     <table class="table" id="myTable">
        <thead>
           <tr>
              <th>Code</th>
              <th>Name</th>
              <th>Price</th>
              <th>Description</th>
              <th>Company Name</th>
              <th class="text-center">Actions</th>
           </tr>
        </thead>
        <tbody>
           <% @c_trash.each do |p| %>
           <tr>
              <td><%= p.code %></td>
              <td><%= p.name %></td>
              <td><%= p.price %></td>
              <td><%= p.description%></td>
              <% if p.Company_id.inspect %>
              <% a = p.Company_id
                 @cmp = Company.find_by_id(a)
              %>
                <td><a href="<%= company_path(:id => @cmp.id)%>"><%= @cmp.name %></a></td>
              <% end %>
              <td class="text-center">
                 <ul class="icons-list">
                    <li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       <i class="icon-menu9"></i>
                       </a>
                       <ul class="dropdown-menu dropdown-menu-right">
                          <li><a href="<%= product_path(:id=>p.id)%>" data-method="delete" data-confirm="Are you sure?" id="sweet_combine"><i class="icon-bin2">
                             </i>
                             Hard-Delete</a>
                          </li>
                          <li><a href="<%= restore_products_path(:id=>p.id)%>"><i class="icon-git-compare"></i>Restore Company</a>
                          </li>                          
                       </ul>
                    </li>
                 </ul>
              </td>
           </tr>
           <%end%>                   
        </tbody>
     </table>
     <tr>
</div>
<script type="text/javascript">
   $(document).ready(function(){
     $('#myTable').DataTable({
      autoWidth: false,
        // columnDefs: [{ 
        //     orderable: false,
        //     width: '100px',
        //     targets: [ 5 ]
        // }],
        dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
        language: {
            search: '<span>Filter:</span> _INPUT_',
            lengthMenu: '<span>Show:</span> _MENU_',
            paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
        drawCallback: function () {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
        },
        preDrawCallback: function() {
            $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
        }
     });
     // Alternative pagination
    $('.datatable-pagination').DataTable({
        pagingType: "simple",
        language: {
            paginate: {'next': 'Next &rarr;', 'previous': '&larr; Prev'}
        }
    });


    // Add placeholder to the datatable filter option
    $('.dataTables_filter input[type=search]').attr('placeholder','Type to filter...');


    // Enable Select2 select for the length option
    $('.dataTables_length select').select2({
        minimumResultsForSearch: Infinity,
        width: 'auto'
    });

   });
</script>